name: rhometa
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy>=1.21,<1.22
  - pandas
  - scipy
  - pysam
  - seaborn
  - numba
  - tqdm
  - bcftools
  - freebayes>=1.3.6
  - samtools=1.12
