name: rhometa
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy=1.21
  - pandas
  - scipy
  - pysam
  - seaborn
  - numba
  - tqdm
  - freebayes=1.3.5
  - samtools==1.12
  - bcftools==1.12
