name: rhometa
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy>=1.21,<1.22
  - pandas
  - biopython
  - scipy
  - future
  - seq-gen
  - bwa
  - samtools=1.15
  - lofreq
  - pysam
  - seaborn
  - numba
  - fastsimbac
  - msprime>=1.1.0
  - bcftools
  - freebayes
  - tqdm
