name: rhometa
channels:
  - bioconda
  - conda-forge
dependencies:
 - 'python=3.10' 
 - 'numpy=1.23' 
 - 'pandas=1.5' 
 - 'scipy=1.9' 
 - 'seaborn=0.11' 
 - 'numba=0.56' 
 - 'tqdm=4.64' 
 - 'bcftools=1.16' 
 - 'bwa-mem2=2.2.1' 
 - 'pysam=0.19' 
 - 'freebayes=1.3.6' 
 - 'samtools=1.16' 
 - 'openssl>=1.1.1q' 
 - 'ncurses>=6.3'