name: rhometa
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.9
  - numpy=1.21
  - pandas
  - scipy
  - seaborn
  - numba
  - tqdm
  - pysam>=0.17
  - freebayes>=1.3.5
  - samtools==1.15
  - openssl=1.1.1n