name: rhometa
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy>=1.21
  - pandas>=1.4.0
  - biopython
  - scipy
  - future
  - bwa
  - samtools>=1.15
  - pysam
  - seaborn
  - numba
  - msprime>=1.1.0
  - tqdm
  - bcftools
  - freebayes>=1.3.6