name: rhometa
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - biopython
  - scipy
  - future
  - seq-gen
  - bwa
  - samtools=1.12
  - pysam
  - seaborn
  - numba
  - fastsimbac